# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "14"

#       - name: Install dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Deploy to Hostinger
#         uses: SamKirkland/FTP-Deploy-Action@4.0.0
#         with:
#           server: ${{ secrets.HOSTINGER_SERVER }}
#           username: ${{ secrets.HOSTINGER_USERNAME }}
#           password: ${{ secrets.HOSTINGER_PASSWORD }}
#           local-dir: ./build/
#           # server-dir: /public_html

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to 'build' branch
        run: |
          git checkout -B build
          git add .
          git commit -m "Build update"
          git push origin build
